export const API_ENDPOINTS = {
  BASE_URL: "https://api.propstack.de",
  CONTACTS_CREATE: "/v1/contacts",
  CONTACTS_DELETE: (id: string) => `/v1/contacts/${id}`,
  CONTACTS_GET: (id: string) => `/v1/contacts/${id}`,
  CONTACTS_GET_ALL: "/v1/contacts",
  CONTACTS_UPDATE: (id: string) => `/v1/contacts/${id}`,
  PROPERTIES_CREATE: "/v1/units",
  PROPERTIES_DELETE: (id: string) => `/v1/units/${id}`,
  PROPERTIES_GET: (id: string) => `/v1/units/${id}`,
  PROPERTIES_GET_ALL: "/v1/units",
  PROPERTIES_UPDATE: (id: string) => `/v1/units/${id}`,
  PROPERTY_STATUSES_GET_ALL: "/v1/property_statuses",
  DEALS_CREATE: "/v1/client_properties",
  DEALS_DELETE: (id: string) => `/v1/client_properties/${id}`,
  DEALS_GET: (id: string) => `/v1/client_properties/${id}`,
  DEALS_GET_ALL: "/v1/client_properties",
  DEALS_UPDATE: (id: string) => `/v1/client_properties/${id}`,
  EMAILS_SEND: "/v1/messages",
  EMAILS_GET: (id: string) => `/v1/messages/${id}`,
  EMAILS_GET_ALL: "/v1/messages",
  EMAILS_UPDATE: (id: string) => `/v1/messages/${id}`,
  DOCUMENTS_CREATE: "/v1/documents",
  DOCUMENTS_DELETE: (id: string) => `/v1/documents/${id}`,
  DOCUMENTS_GET: (id: string) => `/v1/documents/${id}`,
  DOCUMENTS_GET_ALL: "/v1/documents",
  DOCUMENTS_UPDATE: (id: string) => `/v1/documents/${id}`,
  DOCUMENTS_TAGS_GET_ALL: "/v1/documents/tags",
  PROJECTS_CREATE: "/v1/projects",
  PROJECTS_DELETE: (id: string) => `/v1/projects/${id}`,
  PROJECTS_GET: (id: string) => `/v1/projects/${id}`,
  PROJECTS_GET_ALL: "/v1/projects",
  PROJECTS_UPDATE: (id: string) => `/v1/projects/${id}`,
  TASKS_CREATE: "/v1/tasks",
  TASKS_DELETE: (id: string) => `/v1/tasks/${id}`,
  TASKS_GET: (id: string) => `/v1/tasks/${id}`,
  TASKS_GET_ALL: "/v1/tasks",
  TASKS_UPDATE: (id: string) => `/v1/tasks/${id}`,
  TEAMS_CREATE: "/v1/teams",
  TEAMS_DELETE: (id: string) => `/v1/teams/${id}`,
  TEAMS_GET: (id: string) => `/v1/teams/${id}`,
  TEAMS_GET_ALL: "/v1/teams",
  TEAMS_UPDATE: (id: string) => `/v1/teams/${id}`,
  ACTIVITIES_GET: (id: string) => `/v1/activities/${id}`,
  ACTIVITIES_GET_ALL: "/v1/activities",
  ACTIVITY_TYPES_GET_ALL: "/v1/activity_types",
  RESERVATION_REASONS_GET_ALL: "/v1/reservation_reasons",
  CUSTOM_FIELDS_GET_ALL: "/v1/custom_field_groups",
  DEAL_PIPELINES_GET: (id: string) => `/v1/deal_pipelines/${id}`,
  DEAL_PIPELINES_GET_ALL: "/v1/deal_pipelines",
  LOCATIONS_GET_ALL: "/v1/locations",
  FEATURES_CREATE: "/v1/groups",
  FEATURES_GET_ALL: "/v1/groups",
  FEATURES_PARENT_GET_ALL: "/v1/super_groups",
  BROKERS_GET_ALL: "/v1/brokers",
  PORTAL_EXPORT: "/v1/portals/publish",
  SEARCH_PROFILES_CREATE: "/v1/saved_queries",
  SEARCH_PROFILES_DELETE: (id: string) => `/v1/saved_queries/${id}`,
  SEARCH_PROFILES_GET_ALL: "/v1/saved_queries",
  SEARCH_PROFILES_UPDATE: (id: string) => `/v1/saved_queries/${id}`,
  EVENTS_GET_ALL: "/v1/events",
  NOTES_GET_ALL: "/v1/notes",
  WEBHOOKS_CREATE: "/v1/hooks",
  WEBHOOKS_DELETE: (id: string) => `/v1/hooks/${id}`,
  WEBHOOKS_GET_ALL: "/v1/hooks",
};
