import type { INodeProperties } from "n8n-workflow";

export const propertyFieldOptions: INodeProperties[] = [
  {
    displayName: "Additional Area",
    name: "additional_area",
    type: "number",
    default: 0,
  },
  {
    displayName: "Air Conditioning",
    name: "air_conditioning",
    type: "boolean",
    default: false,
    description: "Whether the property has air conditioning",
  },
  {
    displayName: "Alarm System",
    name: "alarm_system",
    type: "boolean",
    default: false,
    description: "Whether the property has an alarm system",
  },
  {
    displayName: "Apartment Number",
    name: "apartment_number",
    type: "string",
    default: "",
  },
  {
    displayName: "Apartment Type",
    name: "apartment_type",
    type: "string",
    default: "",
  },
  {
    displayName: "Archived",
    name: "archived",
    type: "boolean",
    default: false,
    description: "Whether the record is archived",
  },
  {
    displayName: "Auto Lift",
    name: "auto_lift",
    type: "boolean",
    default: false,
    description: "Whether the property has an automatic lift",
  },
  {
    displayName: "Balcony",
    name: "balcony",
    type: "boolean",
    default: false,
    description: "Whether the property has a balcony",
  },
  {
    displayName: "Balcony Space",
    name: "balcony_space",
    type: "number",
    default: 0,
  },
  {
    displayName: "Barrier Free",
    name: "barrier_free",
    type: "boolean",
    default: false,
    description: "Whether the property is barrier-free",
  },
  {
    displayName: "Base Rent",
    name: "base_rent",
    type: "number",
    default: 0,
  },
  {
    displayName: "Bathroom",
    name: "bathroom",
    type: "string",
    default: "",
  },
  {
    displayName: "Broker ID",
    name: "broker_id",
    type: "string",
    default: "",
  },
  {
    displayName: "Broker IDs",
    name: "broker_ids",
    type: "string",
    default: "",
    description: "Comma-separated list of broker IDs",
  },
  {
    displayName: "Building Energy Rating Type",
    name: "building_energy_rating_type",
    type: "string",
    default: "",
  },
  {
    displayName: "Building Permission",
    name: "building_permission",
    type: "string",
    default: "",
  },
  {
    displayName: "Building Type",
    name: "building_type",
    type: "string",
    default: "",
  },
  {
    displayName: "Built-In Kitchen",
    name: "built_in_kitchen",
    type: "boolean",
    default: false,
    description: "Whether the property has a built-in kitchen",
  },
  {
    displayName: "Cellar",
    name: "cellar",
    type: "boolean",
    default: false,
    description: "Whether the property has a cellar",
  },
  {
    displayName: "Cellar Space",
    name: "cellar_space",
    type: "number",
    default: 0,
  },
  {
    displayName: "Chimney",
    name: "chimney",
    type: "boolean",
    default: false,
    description: "Whether the property has a chimney",
  },
  {
    displayName: "City",
    name: "city",
    type: "string",
    default: "",
  },
  {
    displayName: "CO2 Emission",
    name: "co2_emission",
    type: "number",
    default: 0,
  },
  {
    displayName: "Co-Ownership Share",
    name: "co_ownership_share",
    type: "number",
    default: 0,
  },
  {
    displayName: "Commercialization Type",
    name: "commercialization_type",
    type: "string",
    default: "",
  },
  {
    displayName: "Compensation Costs",
    name: "compensation_costs",
    type: "number",
    default: 0,
  },
  {
    displayName: "Condition",
    name: "condition",
    type: "string",
    default: "",
  },
  {
    displayName: "Connected Load",
    name: "connected_load",
    type: "number",
    default: 0,
  },
  {
    displayName: "Construction Phase",
    name: "construction_phase",
    type: "string",
    default: "",
  },
  {
    displayName: "Construction Type",
    name: "construction_type",
    type: "string",
    default: "",
  },
  {
    displayName: "Construction Year",
    name: "construction_year",
    type: "number",
    default: 0,
  },
  {
    displayName: "Contract Type",
    name: "contract_type",
    type: "string",
    default: "",
  },
  {
    displayName: "Corridor",
    name: "corridor",
    type: "boolean",
    default: false,
    description: "Whether the property has a corridor",
  },
  {
    displayName: "Cost Balcony",
    name: "cost_balcony",
    type: "number",
    default: 0,
  },
  {
    displayName: "Cost Lift",
    name: "cost_lift",
    type: "number",
    default: 0,
  },
  {
    displayName: "Cost Other",
    name: "cost_other",
    type: "number",
    default: 0,
  },
  {
    displayName: "Country",
    name: "country",
    type: "string",
    default: "",
  },
  {
    displayName: "Courtage",
    name: "courtage",
    type: "string",
    default: "",
  },
  {
    displayName: "Courtage Note",
    name: "courtage_note",
    type: "string",
    default: "",
    typeOptions: { rows: 4 },
  },
  {
    displayName: "Crane Runway Load",
    name: "crane_runway_load",
    type: "number",
    default: 0,
  },
  {
    displayName: "Cubature",
    name: "cubature",
    type: "number",
    default: 0,
  },
  {
    displayName: "Currency",
    name: "currency",
    type: "string",
    default: "",
  },
  {
    displayName: "Department IDs",
    name: "department_ids",
    type: "string",
    default: "",
    description: "Comma-separated list of department IDs",
  },
  {
    displayName: "Deposit",
    name: "deposit",
    type: "number",
    default: 0,
  },
  {
    displayName: "Description Note",
    name: "description_note",
    type: "string",
    default: "",
    typeOptions: { rows: 4 },
  },
  {
    displayName: "Distance to Airport",
    name: "distance_to_airport",
    type: "number",
    default: 0,
  },
  {
    displayName: "Distance to Airport in KM",
    name: "distance_to_airport_in_km",
    type: "number",
    default: 0,
  },
  {
    displayName: "Distance to FM",
    name: "distance_to_fm",
    type: "number",
    default: 0,
  },
  {
    displayName: "Distance to FM in KM",
    name: "distance_to_fm_in_km",
    type: "number",
    default: 0,
  },
  {
    displayName: "Distance to MRS",
    name: "distance_to_mrs",
    type: "number",
    default: 0,
  },
  {
    displayName: "Distance to MRS in KM",
    name: "distance_to_mrs_in_km",
    type: "number",
    default: 0,
  },
  {
    displayName: "Distance to PT",
    name: "distance_to_pt",
    type: "number",
    default: 0,
  },
  {
    displayName: "Distance to PT in KM",
    name: "distance_to_pt_in_km",
    type: "number",
    default: 0,
  },
  {
    displayName: "Energy Certificate Availability",
    name: "energy_certificate_availability",
    type: "string",
    default: "",
  },
  {
    displayName: "Energy Certificate Creation Date",
    name: "energy_certificate_creation_date",
    type: "dateTime",
    default: "",
  },
  {
    displayName: "Energy Certificate End Date",
    name: "energy_certificate_end_date",
    type: "dateTime",
    default: "",
  },
  {
    displayName: "Energy Certificate Start Date",
    name: "energy_certificate_start_date",
    type: "dateTime",
    default: "",
  },
  {
    displayName: "Energy Consumption Contains Warm Water",
    name: "energy_consumption_contains_warm_water",
    type: "boolean",
    default: false,
    description: "Whether the energy consumption value includes warm water",
  },
  {
    displayName: "Energy Efficiency Class",
    name: "energy_efficiency_class",
    type: "string",
    default: "",
  },
  {
    displayName: "Energy Efficiency Value",
    name: "energy_efficiency_value",
    type: "string",
    default: "",
  },
  {
    displayName: "Equipment Technology Construction Year",
    name: "equipment_technology_construction_year",
    type: "number",
    default: 0,
  },
  {
    displayName: "Exposee ID",
    name: "exposee_id",
    type: "string",
    default: "",
  },
  {
    displayName: "Financial Contribution",
    name: "financial_contribution",
    type: "number",
    default: 0,
  },
  {
    displayName: "Firing Types",
    name: "firing_types",
    type: "string",
    default: "",
  },
  {
    displayName: "Flat Share Suitable",
    name: "flat_share_suitable",
    type: "boolean",
    default: false,
    description: "Whether the property is suitable for a flat share",
  },
  {
    displayName: "Floor",
    name: "floor",
    type: "number",
    default: 0,
  },
  {
    displayName: "Floor Load",
    name: "floor_load",
    type: "number",
    default: 0,
  },
  {
    displayName: "Floor Position",
    name: "floor_position",
    type: "string",
    default: "",
  },
  {
    displayName: "Flooring Type",
    name: "flooring_type",
    type: "string",
    default: "",
  },
  {
    displayName: "Free From",
    name: "free_from",
    type: "dateTime",
    default: "",
  },
  {
    displayName: "Free Until",
    name: "free_until",
    type: "dateTime",
    default: "",
  },
  {
    displayName: "Furnishing Note",
    name: "furnishing_note",
    type: "string",
    default: "",
    typeOptions: { rows: 4 },
  },
  {
    displayName: "Garage Type",
    name: "garage_type",
    type: "string",
    default: "",
  },
  {
    displayName: "Garden",
    name: "garden",
    type: "boolean",
    default: false,
    description: "Whether the property has a garden",
  },
  {
    displayName: "Garden Space",
    name: "garden_space",
    type: "number",
    default: 0,
  },
  {
    displayName: "GFZ",
    name: "gfz",
    type: "number",
    default: 0,
  },
  {
    displayName: "Goods Lift",
    name: "goods_lift",
    type: "boolean",
    default: false,
    description: "Whether the property has a goods lift",
  },
  {
    displayName: "Goods Lift Load",
    name: "goods_lift_load",
    type: "number",
    default: 0,
  },
  {
    displayName: "Group IDs",
    name: "group_ids",
    type: "string",
    default: "",
    description: "Comma-separated list of group IDs",
  },
  {
    displayName: "GRZ",
    name: "grz",
    type: "number",
    default: 0,
  },
  {
    displayName: "Guest Toilet",
    name: "guest_toilet",
    type: "boolean",
    default: false,
    description: "Whether the property has a guest toilet",
  },
  {
    displayName: "Hall Height",
    name: "hall_height",
    type: "number",
    default: 0,
  },
  {
    displayName: "Has Canteen",
    name: "has_canteen",
    type: "boolean",
    default: false,
    description: "Whether the property has a canteen",
  },
  {
    displayName: "Has Furniture",
    name: "has_furniture",
    type: "boolean",
    default: false,
    description: "Whether the property is furnished",
  },
  {
    displayName: "Heating Costs",
    name: "heating_costs",
    type: "number",
    default: 0,
  },
  {
    displayName: "Heating Costs in Service Charge",
    name: "heating_costs_in_service_charge",
    type: "boolean",
    default: false,
    description: "Whether heating costs are included in the service charge",
  },
  {
    displayName: "Heating Type",
    name: "heating_type",
    type: "string",
    default: "",
  },
  {
    displayName: "Height Garage",
    name: "height_garage",
    type: "number",
    default: 0,
  },
  {
    displayName: "Hide Address",
    name: "hide_address",
    type: "boolean",
    default: false,
    description: "Whether to hide the address",
  },
  {
    displayName: "House Number",
    name: "house_number",
    type: "string",
    default: "",
  },
  {
    displayName: "Industrial Area",
    name: "industrial_area",
    type: "number",
    default: 0,
  },
  {
    displayName: "Interior Quality",
    name: "interior_quality",
    type: "string",
    default: "",
  },
  {
    displayName: "Internal Brokerage",
    name: "internal_brokerage",
    type: "boolean",
    default: false,
    description: "Whether this is an internal brokerage",
  },
  {
    displayName: "Investment Type",
    name: "investment_type",
    type: "string",
    default: "",
  },
  {
    displayName: "LAN Cables",
    name: "lan_cables",
    type: "boolean",
    default: false,
    description: "Whether the property has LAN cable connections",
  },
  {
    displayName: "Last Refurbishment",
    name: "last_refurbishment",
    type: "number",
    default: 0,
  },
  {
    displayName: "Latitude",
    name: "lat",
    type: "number",
    default: 0,
  },
  {
    displayName: "Length Garage",
    name: "length_garage",
    type: "number",
    default: 0,
  },
  {
    displayName: "Lift",
    name: "lift",
    type: "boolean",
    default: false,
    description: "Whether the property has a lift",
  },
  {
    displayName: "Living Space",
    name: "living_space",
    type: "number",
    default: 0,
  },
  {
    displayName: "Location Classification Type",
    name: "location_classification_type",
    type: "string",
    default: "",
  },
  {
    displayName: "Location Note",
    name: "location_note",
    type: "string",
    default: "",
    typeOptions: { rows: 4 },
  },
  {
    displayName: "Lodger Flat",
    name: "lodger_flat",
    type: "boolean",
    default: false,
    description: "Whether the property has a lodger flat",
  },
  {
    displayName: "Loggia",
    name: "loggia",
    type: "boolean",
    default: false,
    description: "Whether the property has a loggia",
  },
  {
    displayName: "Long Description Note",
    name: "long_description_note",
    type: "string",
    default: "",
    typeOptions: { rows: 4 },
  },
  {
    displayName: "Long Furnishing Note",
    name: "long_furnishing_note",
    type: "string",
    default: "",
    typeOptions: { rows: 4 },
  },
  {
    displayName: "Long Location Note",
    name: "long_location_note",
    type: "string",
    default: "",
    typeOptions: { rows: 4 },
  },
  {
    displayName: "Long Other Note",
    name: "long_other_note",
    type: "string",
    default: "",
    typeOptions: { rows: 4 },
  },
  {
    displayName: "Longitude",
    name: "lng",
    type: "number",
    default: 0,
  },
  {
    displayName: "Maintenance Reserve",
    name: "maintenance_reserve",
    type: "number",
    default: 0,
  },
  {
    displayName: "Marketing Type",
    name: "marketing_type",
    type: "string",
    default: "",
  },
  {
    displayName: "Max Number of Persons",
    name: "max_number_of_persons",
    type: "number",
    default: 0,
  },
  {
    displayName: "Max Rental Time",
    name: "max_rental_time",
    type: "number",
    default: 0,
  },
  {
    displayName: "Min Rental Time",
    name: "min_rental_time",
    type: "number",
    default: 0,
  },
  {
    displayName: "Monument",
    name: "monument",
    type: "boolean",
    default: false,
    description: "Whether the property is a listed monument",
  },
  {
    displayName: "Net Floor Space",
    name: "net_floor_space",
    type: "number",
    default: 0,
  },
  {
    displayName: "Non-Smoker",
    name: "non_smoker",
    type: "boolean",
    default: false,
    description: "Whether the property is for non-smokers only",
  },
  {
    displayName: "Number of Apartments",
    name: "number_of_apartments",
    type: "number",
    default: 0,
  },
  {
    displayName: "Number of Balconies",
    name: "number_of_balconies",
    type: "number",
    default: 0,
  },
  {
    displayName: "Number of Bathrooms",
    name: "number_of_bath_rooms",
    type: "number",
    default: 0,
  },
  {
    displayName: "Number of Bedrooms",
    name: "number_of_bed_rooms",
    type: "number",
    default: 0,
  },
  {
    displayName: "Number of Commercials",
    name: "number_of_commercials",
    type: "number",
    default: 0,
  },
  {
    displayName: "Number of Floors",
    name: "number_of_floors",
    type: "number",
    default: 0,
  },
  {
    displayName: "Number of Indoor Parking Spaces",
    name: "number_of_indoor_parking_spaces",
    type: "number",
    default: 0,
  },
  {
    displayName: "Number of Outdoor Parking Spaces",
    name: "number_of_outdoor_parking_spaces",
    type: "number",
    default: 0,
  },
  {
    displayName: "Number of Parking Spaces",
    name: "number_of_parking_spaces",
    type: "number",
    default: 0,
  },
  {
    displayName: "Number of Rooms",
    name: "number_of_rooms",
    type: "number",
    default: 0,
  },
  {
    displayName: "Number of Terraces",
    name: "number_of_terraces",
    type: "number",
    default: 0,
  },
  {
    displayName: "Number of Units",
    name: "number_of_units",
    type: "number",
    default: 0,
  },
  {
    displayName: "Number Seats",
    name: "number_seats",
    type: "number",
    default: 0,
  },
  {
    displayName: "Object Type",
    name: "object_type",
    type: "string",
    default: "",
  },
  {
    displayName: "Other Costs",
    name: "other_costs",
    type: "number",
    default: 0,
  },
  {
    displayName: "Other Note",
    name: "other_note",
    type: "string",
    default: "",
    typeOptions: { rows: 4 },
  },
  {
    displayName: "Parking Space Number",
    name: "parking_space_number",
    type: "number",
    default: 0,
  },
  {
    displayName: "Parking Space Price",
    name: "parking_space_price",
    type: "number",
    default: 0,
  },
  {
    displayName: "Parking Space Type",
    name: "parking_space_type",
    type: "string",
    default: "",
  },
  {
    displayName: "Parking Space Types",
    name: "parking_space_types",
    type: "string",
    default: "",
  },
  {
    displayName: "Partial Custom Fields",
    name: "partial_custom_fields",
    type: "string",
    default: "",
    description: "Custom fields as JSON object",
  },
  {
    displayName: "Pets Allowed",
    name: "pets_allowed",
    type: "boolean",
    default: false,
    description: "Whether pets are allowed in the property",
  },
  {
    displayName: "Plot Area",
    name: "plot_area",
    type: "number",
    default: 0,
  },
  {
    displayName: "Plot Number",
    name: "plot_number",
    type: "string",
    default: "",
  },
  {
    displayName: "Plus VAT",
    name: "plus_vat",
    type: "boolean",
    default: false,
    description: "Whether the price is plus VAT",
  },
  {
    displayName: "Price",
    name: "price",
    type: "number",
    default: 0,
  },
  {
    displayName: "Price Type",
    name: "price_type",
    type: "string",
    default: "",
  },
  {
    displayName: "Project ID",
    name: "project_id",
    type: "string",
    default: "",
  },
  {
    displayName: "Property Space Value",
    name: "property_space_value",
    type: "number",
    default: 0,
  },
  {
    displayName: "Property Status ID",
    name: "property_status_id",
    type: "string",
    default: "",
  },
  {
    displayName: "Ramp",
    name: "ramp",
    type: "boolean",
    default: false,
    description: "Whether the property has a ramp",
  },
  {
    displayName: "Recommended Use Types",
    name: "recommended_use_types",
    type: "string",
    default: "",
  },
  {
    displayName: "Region",
    name: "region",
    type: "string",
    default: "",
  },
  {
    displayName: "Register Number",
    name: "register_number",
    type: "string",
    default: "",
  },
  {
    displayName: "Rent Durations",
    name: "rent_durations",
    type: "string",
    default: "",
  },
  {
    displayName: "Rent Subsidy",
    name: "rent_subsidy",
    type: "number",
    default: 0,
  },
  {
    displayName: "Rental Income",
    name: "rental_income",
    type: "number",
    default: 0,
  },
  {
    displayName: "Rental Income Actual",
    name: "rental_income_actual",
    type: "number",
    default: 0,
  },
  {
    displayName: "Rental Income Target",
    name: "rental_income_target",
    type: "number",
    default: 0,
  },
  {
    displayName: "Rented",
    name: "rented",
    type: "boolean",
    default: false,
    description: "Whether the property is currently rented",
  },
  {
    displayName: "RS Category",
    name: "rs_category",
    type: "string",
    default: "",
  },
  {
    displayName: "RS Type",
    name: "rs_type",
    type: "string",
    default: "",
  },
  {
    displayName: "Sauna",
    name: "sauna",
    type: "boolean",
    default: false,
    description: "Whether the property has a sauna",
  },
  {
    displayName: "Service Charge",
    name: "service_charge",
    type: "number",
    default: 0,
  },
  {
    displayName: "Shop Window Length",
    name: "shop_window_length",
    type: "number",
    default: 0,
  },
  {
    displayName: "Short-Term Accommodation Type",
    name: "short_term_accomodation_type",
    type: "string",
    default: "",
  },
  {
    displayName: "Short-Term Constructible",
    name: "short_term_constructible",
    type: "boolean",
    default: false,
    description: "Whether the property is constructible in the short term",
  },
  {
    displayName: "Site Constructible Type",
    name: "site_constructible_type",
    type: "string",
    default: "",
  },
  {
    displayName: "Site Development Type",
    name: "site_development_type",
    type: "string",
    default: "",
  },
  {
    displayName: "Sold Date",
    name: "sold_date",
    type: "dateTime",
    default: "",
  },
  {
    displayName: "Sold Price",
    name: "sold_price",
    type: "number",
    default: 0,
  },
  {
    displayName: "Start Rental Date",
    name: "start_rental_date",
    type: "dateTime",
    default: "",
  },
  {
    displayName: "Store Type",
    name: "store_type",
    type: "string",
    default: "",
  },
  {
    displayName: "Storeroom",
    name: "storeroom",
    type: "boolean",
    default: false,
    description: "Whether the property has a storeroom",
  },
  {
    displayName: "Street",
    name: "street",
    type: "string",
    default: "",
  },
  {
    displayName: "Summer Residence Practical",
    name: "summer_residence_practical",
    type: "boolean",
    default: false,
    description: "Whether the property is suitable as a summer residence",
  },
  {
    displayName: "Supply Type",
    name: "supply_type",
    type: "string",
    default: "",
  },
  {
    displayName: "Swimming Pool",
    name: "swimming_pool",
    type: "boolean",
    default: false,
    description: "Whether the property has a swimming pool",
  },
  {
    displayName: "Team ID",
    name: "team_id",
    type: "string",
    default: "",
  },
  {
    displayName: "Tenancy",
    name: "tenancy",
    type: "string",
    default: "",
  },
  {
    displayName: "Thermal Characteristic Electricity",
    name: "thermal_characteristic_electricity",
    type: "string",
    default: "",
  },
  {
    displayName: "Thermal Characteristic Heating",
    name: "thermal_characteristic_heating",
    type: "string",
    default: "",
  },
  {
    displayName: "Title",
    name: "title",
    type: "string",
    default: "",
  },
  {
    displayName: "Total Floor Space",
    name: "total_floor_space",
    type: "number",
    default: 0,
  },
  {
    displayName: "Total Rent",
    name: "total_rent",
    type: "number",
    default: 0,
  },
  {
    displayName: "Unit ID",
    name: "unit_id",
    type: "string",
    default: "",
  },
  {
    displayName: "Usable Floor Space",
    name: "usable_floor_space",
    type: "number",
    default: 0,
  },
  {
    displayName: "Utilization Trade Site",
    name: "utilization_trade_site",
    type: "string",
    default: "",
  },
  {
    displayName: "Width Garage",
    name: "width_garage",
    type: "number",
    default: 0,
  },
  {
    displayName: "Winter Garden",
    name: "winter_garden",
    type: "boolean",
    default: false,
    description: "Whether the property has a winter garden",
  },
  {
    displayName: "Zip Code",
    name: "zip_code",
    type: "string",
    default: "",
  },
];

export const PROPERTY_DIRECT_FIELDS = [
  "additional_area", "air_conditioning", "alarm_system", "apartment_number",
  "apartment_type", "auto_lift", "balcony", "balcony_space", "barrier_free",
  "base_rent", "bathroom", "building_energy_rating_type", "building_permission",
  "building_type", "built_in_kitchen", "cellar", "cellar_space", "chimney",
  "city", "co2_emission", "co_ownership_share", "commercialization_type",
  "compensation_costs", "condition", "connected_load", "construction_phase",
  "construction_type", "construction_year", "contract_type", "corridor",
  "cost_balcony", "cost_lift", "cost_other", "country", "courtage",
  "courtage_note", "crane_runway_load", "cubature", "currency", "deposit",
  "description_note", "distance_to_airport", "distance_to_airport_in_km",
  "distance_to_fm", "distance_to_fm_in_km", "distance_to_mrs",
  "distance_to_mrs_in_km", "distance_to_pt", "distance_to_pt_in_km",
  "energy_certificate_availability", "energy_certificate_creation_date",
  "energy_certificate_end_date", "energy_certificate_start_date",
  "energy_consumption_contains_warm_water", "energy_efficiency_class",
  "energy_efficiency_value", "equipment_technology_construction_year",
  "exposee_id", "financial_contribution", "firing_types", "flat_share_suitable",
  "floor", "floor_load", "floor_position", "flooring_type", "free_from",
  "free_until", "furnishing_note", "garage_type", "garden", "garden_space",
  "gfz", "goods_lift", "goods_lift_load", "grz", "guest_toilet", "hall_height",
  "has_canteen", "has_furniture", "heating_costs", "heating_costs_in_service_charge",
  "heating_type", "height_garage", "hide_address", "house_number",
  "industrial_area", "interior_quality", "internal_brokerage", "investment_type",
  "lan_cables", "last_refurbishment", "lat", "length_garage", "lift",
  "living_space", "lng", "location_classification_type", "location_note",
  "lodger_flat", "loggia", "long_description_note", "long_furnishing_note",
  "long_location_note", "long_other_note", "maintenance_reserve",
  "marketing_type", "max_number_of_persons", "max_rental_time", "min_rental_time",
  "monument", "net_floor_space", "non_smoker", "number_of_apartments",
  "number_of_balconies", "number_of_bath_rooms", "number_of_bed_rooms",
  "number_of_commercials", "number_of_floors", "number_of_indoor_parking_spaces",
  "number_of_outdoor_parking_spaces", "number_of_parking_spaces",
  "number_of_rooms", "number_of_terraces", "number_of_units", "number_seats",
  "object_type", "other_costs", "other_note", "parking_space_number",
  "parking_space_price", "parking_space_type", "parking_space_types",
  "pets_allowed", "plot_area", "plot_number", "plus_vat", "price", "price_type",
  "project_id", "property_space_value", "property_status_id", "ramp",
  "recommended_use_types", "region", "register_number", "rent_durations",
  "rent_subsidy", "rental_income", "rental_income_actual", "rental_income_target",
  "rented", "rs_category", "rs_type", "sauna", "service_charge",
  "shop_window_length", "short_term_accomodation_type", "short_term_constructible",
  "site_constructible_type", "site_development_type", "sold_date", "sold_price",
  "start_rental_date", "store_type", "storeroom", "street",
  "summer_residence_practical", "supply_type", "swimming_pool", "team_id",
  "tenancy", "thermal_characteristic_electricity", "thermal_characteristic_heating",
  "title", "total_floor_space", "total_rent", "unit_id", "usable_floor_space",
  "utilization_trade_site", "width_garage", "winter_garden", "zip_code",
  "broker_id", "archived",
];

export const PROPERTY_CSV_FIELDS = [
  "group_ids", "broker_ids", "department_ids",
];

export const PROPERTY_JSON_FIELDS = ["partial_custom_fields"];
