import type { INodeProperties } from "n8n-workflow";

export const clientFieldOptions: INodeProperties[] = [
  {
    displayName: "Academic Title",
    name: "academic_title",
    type: "string",
    default: "",
  },
  {
    displayName: "Archived",
    name: "archived",
    type: "boolean",
    default: false,
    description: "Whether the record is archived",
  },
  {
    displayName: "Bank Account Owner",
    name: "bank_account_owner",
    type: "string",
    default: "",
  },
  {
    displayName: "Bank BIC",
    name: "bank_bic",
    type: "string",
    default: "",
  },
  {
    displayName: "Bank IBAN",
    name: "bank_iban",
    type: "string",
    default: "",
  },
  {
    displayName: "Bank Name",
    name: "bank_name",
    type: "string",
    default: "",
  },
  {
    displayName: "Birth Country",
    name: "birth_country",
    type: "string",
    default: "",
  },
  {
    displayName: "Birth Name",
    name: "birth_name",
    type: "string",
    default: "",
  },
  {
    displayName: "Birth Place",
    name: "birth_place",
    type: "string",
    default: "",
  },
  {
    displayName: "Broker ID",
    name: "broker_id",
    type: "string",
    default: "",
  },
  {
    displayName: "Broker IDs",
    name: "broker_ids",
    type: "string",
    default: "",
    description: "Comma-separated list of broker IDs",
  },
  {
    displayName: "Client Reason ID",
    name: "client_reason_id",
    type: "string",
    default: "",
  },
  {
    displayName: "Client Source ID",
    name: "client_source_id",
    type: "string",
    default: "",
  },
  {
    displayName: "Client Status ID",
    name: "client_status_id",
    type: "string",
    default: "",
  },
  {
    displayName: "Commercial",
    name: "commercial",
    type: "boolean",
    default: false,
    description: "Whether this is a commercial client",
  },
  {
    displayName: "Company",
    name: "company",
    type: "string",
    default: "",
  },
  {
    displayName: "Custom Fields",
    name: "partial_custom_fields",
    type: "string",
    default: "",
    description: "Custom fields as JSON object",
  },
  {
    displayName: "Date of Birth",
    name: "dob",
    type: "dateTime",
    default: "",
  },
  {
    displayName: "Department IDs",
    name: "department_ids",
    type: "string",
    default: "",
    description: "Comma-separated list of department IDs",
  },
  {
    displayName: "Description",
    name: "description",
    type: "string",
    default: "",
    typeOptions: { rows: 4 },
  },
  {
    displayName: "Emails",
    name: "emails",
    type: "string",
    default: "",
    description: "Comma-separated list of email addresses",
  },
  {
    displayName: "First Name",
    name: "first_name",
    type: "string",
    default: "",
  },
  {
    displayName: "Folder IDs",
    name: "folder_ids",
    type: "string",
    default: "",
    description: "Comma-separated list of folder IDs",
  },
  {
    displayName: "Follow-Up Date",
    name: "followup_date",
    type: "dateTime",
    default: "",
  },
  {
    displayName: "GDPR Status",
    name: "gdpr_status",
    type: "options",
    default: 0,
    options: [
      { name: "Not Set", value: 0 },
      { name: "Accepted", value: 1 },
      { name: "Rejected", value: 2 },
      { name: "Withdrawn", value: 3 },
    ],
  },
  {
    displayName: "Group IDs",
    name: "group_ids",
    type: "string",
    default: "",
    description: "Comma-separated list of group IDs",
  },
  {
    displayName: "Handover Date",
    name: "handover_date",
    type: "dateTime",
    default: "",
  },
  {
    displayName: "Home Cell",
    name: "home_cell",
    type: "string",
    default: "",
  },
  {
    displayName: "Home City",
    name: "home_city",
    type: "string",
    default: "",
  },
  {
    displayName: "Home Country",
    name: "home_country",
    type: "string",
    default: "",
  },
  {
    displayName: "Home House Number",
    name: "home_house_number",
    type: "string",
    default: "",
  },
  {
    displayName: "Home Phone",
    name: "home_phone",
    type: "string",
    default: "",
  },
  {
    displayName: "Home Street",
    name: "home_street",
    type: "string",
    default: "",
  },
  {
    displayName: "Home URL",
    name: "home_url",
    type: "string",
    default: "",
  },
  {
    displayName: "Home Zip Code",
    name: "home_zip_code",
    type: "string",
    default: "",
  },
  {
    displayName: "Identity Number",
    name: "identity_number",
    type: "string",
    default: "",
  },
  {
    displayName: "Income",
    name: "income",
    type: "number",
    default: 0,
  },
  {
    displayName: "Issuing Authority",
    name: "issuing_authority",
    type: "string",
    default: "",
  },
  {
    displayName: "Last Name",
    name: "last_name",
    type: "string",
    default: "",
  },
  {
    displayName: "Legal Form",
    name: "legal_form",
    type: "string",
    default: "",
  },
  {
    displayName: "Locale",
    name: "locale",
    type: "string",
    default: "",
    description: "Language code (e.g. de, en)",
  },
  {
    displayName: "Message Salutation",
    name: "message_salutation",
    type: "string",
    default: "",
  },
  {
    displayName: "Nationality",
    name: "nationality",
    type: "string",
    default: "",
  },
  {
    displayName: "Newsletter",
    name: "newsletter",
    type: "boolean",
    default: false,
    description: "Whether the client is subscribed to the newsletter",
  },
  {
    displayName: "Newsletter Unsubscribed",
    name: "newsletter_unsubscribed",
    type: "boolean",
    default: false,
    description: "Whether the client has unsubscribed from the newsletter",
  },
  {
    displayName: "Office Cell",
    name: "office_cell",
    type: "string",
    default: "",
  },
  {
    displayName: "Office City",
    name: "office_city",
    type: "string",
    default: "",
  },
  {
    displayName: "Office Country",
    name: "office_country",
    type: "string",
    default: "",
  },
  {
    displayName: "Office House Number",
    name: "office_house_number",
    type: "string",
    default: "",
  },
  {
    displayName: "Office Phone",
    name: "office_phone",
    type: "string",
    default: "",
  },
  {
    displayName: "Office Street",
    name: "office_street",
    type: "string",
    default: "",
  },
  {
    displayName: "Office URL",
    name: "office_url",
    type: "string",
    default: "",
  },
  {
    displayName: "Office Zip Code",
    name: "office_zip_code",
    type: "string",
    default: "",
  },
  {
    displayName: "Parent ID",
    name: "parent_id",
    type: "string",
    default: "",
  },
  {
    displayName: "Phone",
    name: "phone",
    type: "string",
    default: "",
  },
  {
    displayName: "Position",
    name: "position",
    type: "string",
    default: "",
  },
  {
    displayName: "Preferred Contact Channel",
    name: "preferred_contact_channel",
    type: "string",
    default: "",
  },
  {
    displayName: "Preferred Contact Time",
    name: "preferred_contact_time",
    type: "string",
    default: "",
  },
  {
    displayName: "Project IDs",
    name: "project_ids",
    type: "string",
    default: "",
    description: "Comma-separated list of project IDs",
  },
  {
    displayName: "Property Mailing Wanted",
    name: "property_mailing_wanted",
    type: "boolean",
    default: false,
    description: "Whether the client wants property mailings",
  },
  {
    displayName: "Rating",
    name: "rating",
    type: "number",
    default: 0,
  },
  {
    displayName: "Register Number",
    name: "register_number",
    type: "string",
    default: "",
  },
  {
    displayName: "Rent Date",
    name: "rent_date",
    type: "dateTime",
    default: "",
  },
  {
    displayName: "Salutation",
    name: "salutation",
    type: "options",
    default: "mr",
    options: [
      { name: "Dr", value: "dr" },
      { name: "Mr", value: "mr" },
      { name: "Ms", value: "ms" },
      { name: "Mx", value: "mx" },
      { name: "Prof", value: "prof" },
    ],
  },
  {
    displayName: "Score",
    name: "score",
    type: "number",
    default: 0,
  },
  {
    displayName: "Skip Newsletter",
    name: "skip_newsletter",
    type: "boolean",
    default: false,
    description: "Whether to skip sending the newsletter to this client",
  },
  {
    displayName: "Tax Identification Number",
    name: "tax_identification_number",
    type: "string",
    default: "",
  },
  {
    displayName: "Team ID",
    name: "team_id",
    type: "string",
    default: "",
  },
  {
    displayName: "Warning Notice",
    name: "warning_notice",
    type: "string",
    default: "",
  },
];

export const CLIENT_DIRECT_FIELDS = [
  "first_name", "last_name", "company", "salutation", "broker_id",
  "team_id", "academic_title", "phone", "home_phone", "home_cell",
  "office_phone", "office_cell", "dob", "birth_name", "birth_place",
  "birth_country", "identity_number", "issuing_authority", "nationality",
  "rating", "score", "description", "preferred_contact_time",
  "preferred_contact_channel", "position", "home_street",
  "home_house_number", "home_zip_code", "home_city", "home_country",
  "office_street", "office_house_number", "office_zip_code", "office_city",
  "office_country", "tax_identification_number", "parent_id",
  "client_status_id", "client_source_id", "client_reason_id", "locale",
  "income", "handover_date", "rent_date", "followup_date", "newsletter",
  "newsletter_unsubscribed", "skip_newsletter", "property_mailing_wanted",
  "archived", "message_salutation", "warning_notice", "legal_form",
  "register_number", "home_url", "office_url", "bank_name",
  "bank_account_owner", "bank_iban", "bank_bic", "gdpr_status", "commercial",
];

export const CLIENT_CSV_FIELDS = [
  "broker_ids", "department_ids", "emails", "folder_ids",
  "group_ids", "project_ids",
];

export const CLIENT_JSON_FIELDS = ["partial_custom_fields"];
